### ISSUE TITLE
Please support solarized theme

### ISSUE THREAD

**Issue by moleng09** [q77190858/zotero-pdf-background#1]

**Comment by ekpetrov** [comment]
Dear @q77190858 ,
Thank you so much for this extension!

I am not really fond of green page background, so I wanted to post here a way to change the color as anybody wishes.

1. Go to Zotero directory, where all extensions are kept (in linux it should be something like `~/.zotero/zotero/smth.default/extensions`).
2. Go to `pdf-background@juju.com.xpi`.
3. Edit RGBA code in ./skin/careeye.css, e.g. replace the line with 
`.page .textLayer{background-color:rgba(255,228,196,0.5);}`
4. Edit ./content/ex-df-background.js, line 56. Again, replace the RGBA code with the desired one, e.g. `style.textContent = "#viewer.pdfViewer > .page > .textLayer{display:block;background-color:rgba(255,228,196,0.5);}";` Do not mess up the indentation!
5. Disable the plugin in Zotero, restart Zotero, enable the plugin, restart again.

This is not very convenient solution. However, it may be better than none at the moment.

**Comment by q77190858** [comment]
I have add 5 different background color mode, and also support solarized theme or daytime theme. So it is finished.
