### ISSUE TITLE
Does not work when two-page view (i.e., odd spreads or even spreads) is used

### ISSUE THREAD

**Issue by dschaehi** [q77190858/zotero-pdf-background#10]
When view->odd spreads or view->even spreads are chosen, the PDF color returns to white.

**Comment by MyLotte** [comment]
我也遇到了同样的问题，无论是odd spreads view还是even spreads view插件都会失效，非spreads view（剂单页显示）时可以正常使用

**Comment by q77190858** [comment]
now support split window.
