### ISSUE TITLE
Change default colour

### ISSUE THREAD

**Issue by gabmackie** [q77190858/zotero-pdf-background#13]
I wanted to know if it's possible to change the default background colour? Or set it to stay on the last colour used? I always use the sepia/beige but when I close and reopen Zotero it resets to green.

Love the plugin, thank you!

**Comment by GrayXu** [comment]
unzip the xpi file, and change this line  
`this.setPref("defaultBackground",this.background_list[3]);`

**Comment by q77190858** [comment]
now this plugin can remember the last color you selected when restart.
