### ISSUE TITLE
当zotero开启分屏显示时，插件失效了

### ISSUE THREAD

**Issue by Wrandz** [q77190858/zotero-pdf-background#4]
如图所示
![Snipaste_2022-10-03_16-02-20](https://user-images.githubusercontent.com/70056470/193528761-8d4694ef-01a7-4070-91e5-1995f78bd305.png)

**Comment by q77190858** [comment]
分屏功能我怎么没有呢？

**Comment by Wrandz** [comment]
应该是新版zotero的功能吧，不过我是用的青柠学术的if pro max插件实现的

**Comment by Wrandz** [comment]
@q77190858 
![微信图片_20221101213338](https://user-images.githubusercontent.com/70056470/199245728-7542a4ed-cc7c-43ee-b947-9a6c4e84d897.png)

**Comment by mulei000** [comment]
会和zotero-PDF-translate冲突导致无法翻译...希望可以解决

**Comment by mulei000** [comment]
就是这个样子，开启护眼之后翻译的按键就没有了
感谢回复！








木、磊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "q77190858/zotero-pdf-background"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 上午7:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [q77190858/zotero-pdf-background] 当zotero开启分屏显示时，插件失效了 (Issue #4)





   
没有这个问题呀，我用翻译插件用得挺好的

**Comment by q77190858** [comment]
> 就是这个样子，开启护眼之后翻译的按键就没有了 感谢回复！ 木、磊 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "q77190858/zotero-pdf-background" ***@***.***&gt;; 发送时间:&nbsp;2022年11月9日(星期三) 上午7:59 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [q77190858/zotero-pdf-background] 当zotero开启分屏显示时，插件失效了 (Issue #4) 没有这个问题呀，我用翻译插件用得挺好的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
请开新issue说明，把图片也贴上

**Comment by csf2022scut** [comment]
> 分屏功能我怎么没有呢？

你没更新吧

**Comment by Wrandz** [comment]
更新新版以后，在“查看”中就有一个“横向分割”和“竖向分割”按钮，哎，一分割，就左边起作用，右边不起作用
![Snipaste_2022-12-18_16-22-33](https://user-images.githubusercontent.com/70056470/208288412-54924f79-aab7-411f-baf1-d81be9f3c204.png)
![Snipaste_2022-12-18_16-23-13](https://user-images.githubusercontent.com/70056470/208288421-303967da-5d17-496f-9e02-f8d0f2481ce7.png)

**Comment by aaawrong** [comment]
不修复了嘛这个分屏问题，我也是这样

**Comment by q77190858** [comment]
现在可以分屏了
